apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3s-maintenance

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - cronjob.yaml

labels:
  - pairs:
      app.kubernetes.io/name: pod-cleanup
      app.kubernetes.io/component: maintenance
      app.kubernetes.io/managed-by: kustomize
