apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  app: postgres

# Note: Secret must be created manually or via script
# See secret.yaml.example for instructions
