apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

resources:
  - namespace.yaml
  - pvc-config.yaml
  - pvc-cache.yaml
  - pvc-media.yaml
  - deployment.yaml
  - service.yaml
  - ingress-external.yaml
  - ingress-local.yaml

commonLabels:
  app: jellyfin
