
apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

 

namespace: homeassistant

 

resources:

  - namespace.yaml

  - deployment.yaml

  - service.yaml

  - ingress-local.yaml

  - ingress-external.yaml

  - pvc.yaml

 

commonLabels:

  app: homeassistant

